spring:
  application:
    name: e-commerce
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/e_redux
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database: postgresql
server:
  port: 8080
  servlet:
    context-path: /api
logging:
  level:
    root: DEBUG
    org:
      springframework:
        security: DEBUG
        web: DEBUG